version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=classic_wow_npcs/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=classic_wow_npcs.config.DevelopmentConfig
    depends_on:
      - api-db

  api-db:
    build:
      context: ./classic_wow_npcs/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres